from enum import Enum

class SoldierState(Enum):
    LOWONPAINT = "LOWONPAINT"
    DELIVERINGMESSAGE = "DELIVERINGMESSAGE"
    FILLINGTOWER = "FILLINGTOWER"
    STUCK = "STUCK"
    EXPLORING = "EXPLORING"
    FILLINGSRP = "FILLINGSRP"
